### ISSUE TITLE
Inconsistency between "ex officio" and "ex-officio"

### ISSUE THREAD

**Issue by sushain97** [CMU-Senate/bylaws#10]

**Comment by nikkiam** [comment]
Easy fix, marked for bundling with the upcoming bylaw changes

**Comment by nikkiam** [comment]
Officially, the spelling is ex officio. I can either go through and fix this, or you can in your typos commit @sushain97. Let me know how you would like to proceed.

**Comment by nikkiam** [comment]
submitted a pull request myself anyways, its fixed
