### ISSUE TITLE
Inconsistency between "ad hoc" and "Ad-Hoc"

### ISSUE THREAD

**Issue by sushain97** [CMU-Senate/bylaws#18]

**Comment by nikkiam** [comment]
Marked to be added into the upcoming proposal.

**Comment by nikkiam** [comment]
To confirm what we will be going with, Ad-Hoc is the wrong spelling and ad hoc is the correct one. All mentions of Ad-Hoc will be replaced.

**Comment by nikkiam** [comment]
on second review, there was only mention of ad hoc and not ad-hoc in the bylaws. I did searches on the document and only found one instance. Can you confirm you were just wondering how to spell it for the one instance?

**Comment by sushain97** [comment]
In that case, I'm not entirely certain what the providence of this issue is. It may have been another one of our policies using alternate spelling.
