### ISSUE TITLE
Typo: "to o assist the Student Body President"

### ISSUE THREAD

**Issue by sushain97** [CMU-Senate/bylaws#20]
Currently uncertain whether this is an artifact of the transfer process or original bylaws.

**Comment by nikkiam** [comment]
According to the most recently updated (24 August) policies on the [official website](http://www.cmu.edu/stugov/policies/index.html), this is an official error in the bylaws. Marked to be rolled into proposed bylaw changes.

**Comment by nikkiam** [comment]
Can you add this to your typos pull request and close the issue? @sushain97

**Comment by sushain97** [comment]
> Can you add this to your typos pull request

Done.

> close the issue

Standard procedure is to actually wait until a PR is merged to close the corresponding issue and perhaps add a tag "PR-ready" or something similar until merge. However, since you've been closing the other ones, we can go with that for consistency!
